In [1]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

1.26.4
2.2.3


In [2]:
def column_stats(a):
    b = np.mean(a, axis=0)
    c = np.std(a, axis=0)
    d = np.min(a, axis=0)
    e = np.max(a, axis=0)
    return b, c, d, e

In [3]:
def mask_array(a, b):
    c = np.copy(a)
    c[c > b] = b - 6
    d = np.sum(a > b, axis=1)
    return c, d

In [4]:
def pairwise_distances(a, b):
    c = a[:, np.newaxis, :]
    d = b[np.newaxis, :, :]
    return np.sqrt(np.sum((c - d) ** 2, axis=-1))

In [5]:
def naive_pairwise_distances(a, b):
    c = a.shape[0]
    d = b.shape[0]
    e = np.zeros((c, d))
    for f in range(c):
        for g in range(d):
            e[f, g] = np.sqrt(np.sum((a[f] - b[g]) ** 2))
    return e

a = np.random.default_rng(42)
b = a.random((5, 3))
c = a.random((4, 3))

d = pairwise_distances(b, c)
e = naive_pairwise_distances(b, c)
print(np.allclose(d, e))

True


In [6]:
def closest_row(a, b):
    c = pairwise_distances(a, b)
    return np.argmin(c, axis=1)

print(closest_row(b, c))

[1 3 0 1 1]


In [7]:
def confusion_matrix(a, b):
    a = np.asarray(a)
    b = np.asarray(b)
    c = np.sum((a == 1) & (b == 1))
    d = np.sum((a == 0) & (b == 1))
    e = np.sum((a == 1) & (b == 0))
    f = np.sum((a == 0) & (b == 0))
    return np.array([[f, d], [e, c]])

In [8]:
def binary_metrics(a, b):
    c = confusion_matrix(a, b)
    d, e = c[0]
    f, g = c[1]
    h = g / (g + e) if (g + e) > 0 else 0.0
    i = g / (g + f) if (g + f) > 0 else 0.0
    j = (2 * h * i) / (h + i) if (h + i) > 0 else 0.0
    return h, i, j

In [9]:
def multiclass_confusion_matrix(a, b):
    a = np.asarray(a)
    b = np.asarray(b)
    c = np.unique(np.concatenate((a, b)))
    d = len(c)
    e = np.zeros((d, d), dtype=int)
    for f, g in enumerate(c):
        for h, i in enumerate(c):
            e[f, h] = np.sum((a == g) & (b == i))
    return e, c

In [10]:
def multiclass_metrics(a, b):
    c, d = multiclass_confusion_matrix(a, b)
    e = len(d)
    f = np.zeros(e)
    g = np.zeros(e)
    h = np.zeros(e)
    for i in range(e):
        j = c[i, i]
        k = np.sum(c[:, i]) - j
        l = np.sum(c[i, :]) - j
        m = j / (j + k) if (j + k) > 0 else 0.0
        n = j / (j + l) if (j + l) > 0 else 0.0
        o = (2 * m * n) / (m + n) if (m + n) > 0 else 0.0
        f[i] = m
        g[i] = n
        h[i] = o
    p = np.mean(h)
    return f, g, h, p

In [11]:
a = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0])
b = np.array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1])
c = confusion_matrix(a, b)
print("Binary COnfusion Matrx:\n", c)

d = np.array([0, 1, 2, 0, 1, 2, 0, 2, 2, 1])
e = np.array([0, 2, 1, 0, 1, 2, 0, 2, 1, 1])
f, g = multiclass_confusion_matrix(d, e)
print("Multiclass Confusion Matrix:\n", f)

h, i, j, k = multiclass_metrics(d, e)
print("F1:", k)

Binary COnfusion Matrx:
 [[3 2]
 [1 4]]
Multiclass Confusion Matrix:
 [[3 0 0]
 [0 2 1]
 [0 2 2]]
F1: 0.7142857142857144
