In [5]:
import pandas as pd
import numpy as np


In [7]:
print(np.__version__)
print(pd.__version__)

2.5.1
3.0.5


In [16]:
a1=np.array([[1,2,3],
            [4,5,6]])
a2=np.zeros((5,6))
a3=np.ones(5)
a4=np.arange(5)
a5=np.linspace(5,6,100)
print(a1,a2,a3,a4,a5)

[[1 2 3]
 [4 5 6]] [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] [1. 1. 1. 1. 1.] [0 1 2 3 4] [5.         5.01010101 5.02020202 5.03030303 5.04040404 5.05050505
 5.06060606 5.07070707 5.08080808 5.09090909 5.1010101  5.11111111
 5.12121212 5.13131313 5.14141414 5.15151515 5.16161616 5.17171717
 5.18181818 5.19191919 5.2020202  5.21212121 5.22222222 5.23232323
 5.24242424 5.25252525 5.26262626 5.27272727 5.28282828 5.29292929
 5.3030303  5.31313131 5.32323232 5.33333333 5.34343434 5.35353535
 5.36363636 5.37373737 5.38383838 5.39393939 5.4040404  5.41414141
 5.42424242 5.43434343 5.44444444 5.45454545 5.46464646 5.47474747
 5.48484848 5.49494949 5.50505051 5.51515152 5.52525253 5.53535354
 5.54545455 5.55555556 5.56565657 5.57575758 5.58585859 5.5959596
 5.60606061 5.61616162 5.62626263 5.63636364 5.64646465 5.65656566
 5.66666667 5.67676768 5.68686869 5.6969697  5.70707071 5.71717172
 5.72727273 5.73737374 5.74747475 5.7575757

In [18]:
a6=np.random.default_rng(42)
print(a6)

Generator(PCG64)


In [19]:
a1.ndim

2

In [25]:
a1.reshape(-1)


array([1, 2, 3, 4, 5, 6])

In [28]:
b=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])


In [32]:
print(b.sum(axis=1))


[10 26 42]


In [33]:
c=np.array([1,2,3,4,5,6,7,8,9])

In [34]:
c[2:4]

array([3, 4])

In [36]:
d=c[c>5]
print(d)

[6 7 8 9]


In [39]:
e=a-a.mean()
print(e)

[[-2.5 -1.5 -0.5]
 [ 0.5  1.5  2.5]]


In [41]:
data_features=pd.read_csv("lab1_features.csv")
data_features.head()

,f1,f2,f3,f4,f5
0,-0.7136,43.9184,0.3279,0.2002,0.0134
1,1.6248,26.3853,0.2420,0.3901,-0.1214
2,0.1761,40.0557,0.0086,2.1367,-0.0019
3,1.3590,56.8912,-1.9542,4.8096,0.0579
4,0.4035,49.5661,-1.9010,4.3185,0.0422


In [42]:
data_features.mean()

f1     0.073850
f2    51.221396
f3     0.284653
f4     2.001465
f5     0.003365
dtype: float64

In [44]:
def column_stats(x):
    return np.array(x.mean()),np.array(x.std()),np.array(x.min()),np.array(x.max())
column_stats(data_features)

(array([7.38500000e-02, 5.12213958e+01, 2.84653333e-01, 2.00146500e+00,
        3.36500000e-03]),
 array([ 1.05722574, 10.19333587,  2.80149076,  1.97806108,  0.04890331]),
 array([-2.78280e+00,  2.35173e+01, -4.96900e+00,  2.50000e-03,
        -1.62500e-01]),
 array([ 2.9153, 83.6084,  4.9785, 10.6876,  0.1586]))

In [50]:
def masking(x,t):
    x=np.array(x)
    a=x.copy()
    mask=a>t
    print(mask)
    a=
masking(a1,2)
    

SyntaxError: invalid syntax (1350176599.py, line 5)